# This file sets the Daheng VA-Imaging GigE camera parameters
# THe camera currently uses GStream and Aravis drivers
camera:
  id: "Daheng Imaging-MER2-630-18GC-P-FBJ24120608"

  width: 2620
  height: 1216
  fps: 8
  reconnect:
    max_retries: 3
    sleep_s: 2.0
  profiles:

    day:
      start: "06:00"
      end: "18:00"
      exposure_us: 100000
      gain_db: 5
      gamma_enable: false
      gamma: 0.8

    night:
      start: "18:00"
      end: "06:00"
      exposure_us: 150000
      gain_db: 12
      gamma_enable: false
      gamma: 1.4

  auto_exposure: false
  auto_gain: false